apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygenerator-team-config
placementBindingDefaults:
  name: global-team-config
policyDefaults:
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  remediationAction: enforce
  severity: medium
  namespace: global-policies
  generatePlacementWhenInSet: true
  # orderManifests: true
  # consolidateManifests: false
policies:
- name: policy-che-cluster
  disabled: false
  manifests:
    - path: ./checluster
  placement:
    labelSelector: {}
  extraDependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
      name: openshift-devspaces-installed
- name: policy-team-a-resources
  disabled: false
  manifests:
    - path: ./team-a
  placement:
    labelSelector:
      matchExpressions:
        - key: team-a-cluster
          operator: In
          values:
            - "true"
- name: policy-team-b-resources
  disabled: false
  manifests:
    - path: ./team-b
  placement:
    labelSelector:
      matchExpressions:
        - key: team-b-cluster
          operator: In
          values:
            - "true"




    
