apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygenerator-team-config
placementBindingDefaults:
  name: global-team-config
policyDefaults:
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  remediationAction: enforce
  severity: medium
  namespace: global-policies
  generatePlacementWhenInSet: true
policies:
- name: policy-configurations
  disabled: false
  manifests:
    - path: ./configurations
  placement:
    labelSelector: {}




    
