apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../global-teams/clusterscoped-resources
patches:
- path: ./patches/clusterresourcequota-update.yaml
  target:
    group: quota.openshift.io
    kind: ClusterResourceQuota
    name: for-append-team-name
    version: v1
- path: ./patches/clusterresourcequota-rename.yaml
  target:
    group: quota.openshift.io
    kind: ClusterResourceQuota
    name: for-append-team-name
    version: v1
