apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: working
    apps.open-cluster-management.io/git-path: namespace-kustomize-example2/configurations/global-secret-example-resources
    apps.open-cluster-management.io/reconcile-option: merge
    apps.open-cluster-management.io/reconcile-rate: "off"
  labels:
    app: global-secret-example
  name: sub-channel-global-secret-example
  namespace: global-policies
spec:
  channel: channel-global-secret-example/channel-global-secret-example
  placement:
    clusterSelector: {}
    
