apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-global-secret
  namespace: global-policies
placementRef:
  name: placement-policy-global-secret
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-global-secret
    apiGroup: policy.open-cluster-management.io
    kind: Policy