apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-global-secret
  namespace: global-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector: {}